### ISSUE TITLE
beast xml files do not specify (correct) datatype

### ISSUE THREAD

**Issue by Anaphory** [CompEvol/morph-models#4]
I am trying to run beast with morph-traits, using the latest versions from github [beast: commit 892e22a227b37e4c56eedddd2abe03e3885c8a9e, Fri Mar 13 16:13:06 2015 morph-models: commit c11f1d73d1011012a470f20af92eea2b857832d6, Fri Mar 13 16:28:51 2015]. I am running them from Eclipse's debug mode.

Using both a beauti generated beast xml configuration or `examples/M3982.xml` from this repository, I get the error logs below.

```
File: M3982.xml seed: 127 threads: 1
Probing: beagle.jar Skip loading file:/usr/home/gereon/lang/beast/beast2/lib/beagle.jar: contains classs beagle.Beagle that is already loaded
Probing: colt.jar Skip loading file:/usr/home/gereon/lang/beast/beast2/lib/colt.jar: contains classs cern.clhep.PhysicalConstants that is already loaded
Probing: commons-math3-3.1.1.jar Skip loading file:/usr/home/gereon/lang/beast/beast2/lib/commons-math3-3.1.1.jar: contains classs org.apache.commons.math3.linear.OpenMapRealVector$OpenMapEntry that is already loaded
Probing: debug-1.0.jar Skip loading file:/usr/home/gereon/lang/beast/beast2/lib/debug-1.0.jar: contains classs org.jdesktop.swinghelper.debug.CheckThreadViolationRepaintManager$1 that is already loaded
Probing: fest-sources.jar URL file:/usr/home/gereon/lang/beast/beast2/lib/fest-sources.jar is already in the CLASSPATH
Probing: fest.jar Skip loading file:/usr/home/gereon/lang/beast/beast2/lib/fest.jar: contains classs net.jcip.annotations.GuardedBy that is already loaded
Probing: jam.jar Skip loading file:/usr/home/gereon/lang/beast/beast2/lib/jam.jar: contains classs jam.console.ConsoleApplication$1 that is already loaded
Probing: junit-4.8.2.jar Skip loading file:/usr/home/gereon/lang/beast/beast2/lib/junit-4.8.2.jar: contains classs junit.extensions.ActiveTestSuite$1 that is already loaded
Probing: BDSSM.addon.jar Loaded URL file:/home/gereon/.beast/2.2/BDSKY/lib/BDSSM.addon.jar
Probing: GEO.addon.jar Loaded URL file:/home/gereon/.beast/2.2/GEO_SPHERE/lib/GEO.addon.jar
Probing: SubstBMA.addon.jar Loaded URL file:/home/gereon/.beast/2.2/SubstBMA/lib/SubstBMA.addon.jar
Probing: colt.jar Skip loading file:/home/gereon/.beast/2.2/SubstBMA/lib/colt.jar: contains classs cern.clhep.PhysicalConstants that is already loaded
Uniform => beast.math.distributions.Uniform
Exponential => beast.math.distributions.Exponential
LogNormal => beast.math.distributions.LogNormalDistributionModel
Normal => beast.math.distributions.Normal
Beta => beast.math.distributions.Beta
Gamma => beast.math.distributions.Gamma
LaplaceDistribution => beast.math.distributions.LaplaceDistribution
prior => beast.math.distributions.Prior
InverseGamma => beast.math.distributions.InverseGamma
OneOnX => beast.math.distributions.OneOnX
Alignment(M3982)
  55 taxa
  16 sites
  16 patterns

Filter 1,2,4,7,8,12,15,16
55 taxa
8 sites
8 patterns
java.lang.RuntimeException: number of stationary frequencies does not match number of states.
	at beast.evolution.substitutionmodel.LewisMK.setFrequencies(LewisMK.java:53)
	at beast.evolution.substitutionmodel.LewisMK.initAndValidate(LewisMK.java:82)
	at beast.util.XMLParser.initPlugins(XMLParser.java:314)
	at beast.util.XMLParser.parse(XMLParser.java:443)
	at beast.util.XMLParser.parseFile(XMLParser.java:244)
	at beast.app.BeastMCMC.parseArgs(BeastMCMC.java:253)
	at beast.app.BeastMCMC.parseArgs(BeastMCMC.java:238)
	at beast.app.BeastMCMC.main(BeastMCMC.java:517)

Error 110 parsing the xml input file

validate and intialize error: number of stationary frequencies does not match number of states.

Error detected about here:
  <beast>
      <run id='mcmc' spec='MCMC'>
          <distribution id='posterior' spec='util.CompoundDistribution'>
              <distribution id='likelihood' spec='util.CompoundDistribution'>
                  <distribution id='morphTreeLikelihood.M39822' spec='TreeLikelihood'>
                      <siteModel id='morphSiteModel.s:M39822' spec='SiteModel'>
                          <substModel id='LewisMK.s:M39822' spec='LewisMK'>

data
```

```
File: test.xml seed: 127 threads: 1
Probing: beagle.jar Skip loading file:/usr/home/gereon/lang/beast/beast2/lib/beagle.jar: contains classs beagle.Beagle that is already loaded
Probing: colt.jar Skip loading file:/usr/home/gereon/lang/beast/beast2/lib/colt.jar: contains classs cern.clhep.PhysicalConstants that is already loaded
Probing: commons-math3-3.1.1.jar Skip loading file:/usr/home/gereon/lang/beast/beast2/lib/commons-math3-3.1.1.jar: contains classs org.apache.commons.math3.linear.OpenMapRealVector$OpenMapEntry that is already loaded
Probing: debug-1.0.jar Skip loading file:/usr/home/gereon/lang/beast/beast2/lib/debug-1.0.jar: contains classs org.jdesktop.swinghelper.debug.CheckThreadViolationRepaintManager$1 that is already loaded
Probing: fest-sources.jar URL file:/usr/home/gereon/lang/beast/beast2/lib/fest-sources.jar is already in the CLASSPATH
Probing: fest.jar Skip loading file:/usr/home/gereon/lang/beast/beast2/lib/fest.jar: contains classs net.jcip.annotations.GuardedBy that is already loaded
Probing: jam.jar Skip loading file:/usr/home/gereon/lang/beast/beast2/lib/jam.jar: contains classs jam.console.ConsoleApplication$1 that is already loaded
Probing: junit-4.8.2.jar Skip loading file:/usr/home/gereon/lang/beast/beast2/lib/junit-4.8.2.jar: contains classs junit.extensions.ActiveTestSuite$1 that is already loaded
Probing: BDSSM.addon.jar Loaded URL file:/home/gereon/.beast/2.2/BDSKY/lib/BDSSM.addon.jar
Probing: GEO.addon.jar Loaded URL file:/home/gereon/.beast/2.2/GEO_SPHERE/lib/GEO.addon.jar
Probing: SubstBMA.addon.jar Loaded URL file:/home/gereon/.beast/2.2/SubstBMA/lib/SubstBMA.addon.jar
Probing: colt.jar Skip loading file:/home/gereon/.beast/2.2/SubstBMA/lib/colt.jar: contains classs cern.clhep.PhysicalConstants that is already loaded
Uniform => beast.math.distributions.Uniform
Exponential => beast.math.distributions.Exponential
LogNormal => beast.math.distributions.LogNormalDistributionModel
Normal => beast.math.distributions.Normal
Beta => beast.math.distributions.Beta
Gamma => beast.math.distributions.Gamma
LaplaceDistribution => beast.math.distributions.LaplaceDistribution
prior => beast.math.distributions.Prior
InverseGamma => beast.math.distributions.InverseGamma
OneOnX => beast.math.distributions.OneOnX
java.lang.Exception: Either input 'stateNumber' or 'datatype' needs to be specified
	at beast.core.Input.validate(Input.java:702)
	at beast.core.BEASTInterface.validateInputs(BEASTInterface.java:315)
	at beast.util.XMLParser.createObject(XMLParser.java:697)
	at beast.util.XMLParser.parseInputs(XMLParser.java:830)
	at beast.util.XMLParser.createObject(XMLParser.java:693)
	at beast.util.XMLParser.parseInputs(XMLParser.java:830)
	at beast.util.XMLParser.createObject(XMLParser.java:693)
	at beast.util.XMLParser.parseInputs(XMLParser.java:830)
	at beast.util.XMLParser.createObject(XMLParser.java:693)
	at beast.util.XMLParser.parseInputs(XMLParser.java:830)
	at beast.util.XMLParser.createObject(XMLParser.java:693)
	at beast.util.XMLParser.parseInputs(XMLParser.java:830)
	at beast.util.XMLParser.createObject(XMLParser.java:693)
	at beast.util.XMLParser.parseRunElement(XMLParser.java:561)
	at beast.util.XMLParser.parse(XMLParser.java:442)
	at beast.util.XMLParser.parseFile(XMLParser.java:244)
	at beast.app.BeastMCMC.parseArgs(BeastMCMC.java:253)
	at beast.app.BeastMCMC.parseArgs(BeastMCMC.java:238)
	at beast.app.BeastMCMC.main(BeastMCMC.java:517)

Error 110 parsing the xml input file

validate and intialize error: Either input 'stateNumber' or 'datatype' needs to be specified

Error detected about here:
  <beast>
      <run id='mcmc' spec='MCMC'>
          <distribution id='posterior' spec='util.CompoundDistribution'>
              <distribution id='likelihood' spec='util.CompoundDistribution'>
                  <distribution id='treeLikelihood.anolis' spec='TreeLikelihood'>
                      <siteModel id='SiteModel.s:anolis' spec='SiteModel'>
                          <substModel id='LewisMK.s:anolis' spec='LewisMK'>

```

**Comment by Anaphory** [comment]
The same last 10 lines are shown in an error message when trying to open those xml files in BEAUti.

**Comment by Anaphory** [comment]
The problem seems to lie in the `<parameter>` values: They are all

```
<parameter dimension="4" id="freqParameter.s:M39824" lower="0.0" name="stateNode" upper="1.0">0.25</parameter>
```
but should depend on the specific data, such as

      <parameter dimension="7" id="freqParameter.s:M39827" lower="0.0" name="stateNode" upper="1.0">0.142857142857142857142857142857142857142857</parameter>
      <parameter dimension="6" id="freqParameter.s:M39826" lower="0.0" name="stateNode" upper="1.0">0.166666666666666666666666666666666666666667</parameter>
      <parameter dimension="3" id="freqParameter.s:M39823" lower="0.0" name="stateNode" upper="1.0">0.333333333333333333333333333333333333333333</parameter>
      <parameter dimension="5" id="freqParameter.s:M39825" lower="0.0" name="stateNode" upper="1.0">0.2</parameter>
      <parameter dimension="2" id="freqParameter.s:M39822" lower="0.0" name="stateNode" upper="1.0">0.5</parameter>
      <parameter dimension="4" id="freqParameter.s:M39824" lower="0.0" name="stateNode" upper="1.0">0.25</parameter>
      <parameter dimension="10" id="freqParameter.s:M398210" lower="0.0" name="stateNode" upper="1.0">0.1</parameter>

(Also, what is the best way to specify 1/7 for values like these?)

Pull request to follow.

**Comment by gavryushkina** [comment]
This happened due to incorrect Lewis MK model specification. This model should not have frequencies input then they are not estimated but fixed. The xml is updated now.

**Comment by Anaphory** [comment]
Excellent! Sorry for writing such nonsense in my commit.

**Comment by gavryushkina** [comment]
Thank you for pointing out this.
