### ISSUE TITLE
java.lang.NullPointerException at initialization

### ISSUE THREAD

**Issue by zhangchicool** [CompEvol/morph-models#9]
At the beginning of the run, BEAST2 shows:
java.lang.NullPointerException
	at beast.evolution.likelihood.BeagleTreeLikelihood.setUpSubstModel(BeagleTreeLikelihood.java:474)
	at beast.evolution.likelihood.BeagleTreeLikelihood.initialize(BeagleTreeLikelihood.java:364)
	at beast.evolution.likelihood.BeagleTreeLikelihood.initAndValidate(BeagleTreeLikelihood.java:99)
	at beast.core.BEASTInterface.initByName(BEASTInterface.java:105)
	at beast.evolution.likelihood.TreeLikelihood.initAndValidate(TreeLikelihood.java:132)
	at beast.util.XMLParser.initBEASTObjects(XMLParser.java:377)
	at beast.util.XMLParser.parse(XMLParser.java:535)
	at beast.util.XMLParser.parseFile(XMLParser.java:302)
	at beast.app.BeastMCMC.parseArgs(BeastMCMC.java:311)
	at beast.app.BeastMCMC.main(BeastMCMC.java:567)

although the run will continue and will have results.
A toy xml will reproduce the problem:
[test.xml.zip](https://github.com/CompEvol/morph-models/files/2140565/test.xml.zip)

**Comment by SimonGreenhill** [comment]
BEAGLE can't handle the datatype, a workaround is to disable beagle with the -java flag. This is very slow though

**Comment by zhangchicool** [comment]
The xml was generated by BEAUti, and I seem to notice this exception only recently
